### ISSUE TITLE
`icount` masks the `icount` function from the `iterators` package, but does not include `iterators::icount`'s functionality

### ISSUE THREAD

**Issue by gwerbin** [ramhiser/itertools2#39]
The `iterators` version of `icount` generates integer sequences with a fixed step size of 1, starting from 1, either forever (with no argument) or until a specified stopping point is reached. The `itertools2` version generates infinite integer sequences with a specified step size.

There are two problems with this:

1. `icount` is part of the `iterators` package and not `itertools`, so I don't feel it's appropriate to mask.
2. Loading `itertools2` will _drastically_ alter the behavior of the function, necessitating defensive `::`s everywhere.

I understand that your `icount` function is closer to Python's than `itertools::icount`. Your thoughts?

And by the way, a brief comparison of `itertools` and `itertools2` would be a nice addition to the readme.

**Comment by ramhiser** [comment]
You make some good points. I'll address them later today.

**Comment by ramhiser** [comment]
Before I address the `icount` concern, you make a good point about differentiating `itertools` vs `itertools2` in the readme. I'll post an issue.

**Comment by ramhiser** [comment]
First off, this is an issue that crops up with various packages, e.g., `dplyr` vs `plyr`, `reshape` vs `reshape2`. A quick Google search for **r package mask function** yields multiple results suggesting to use the `::` option. This [Quora post](http://www.quora.com/In-R-how-can-I-make-sure-my-code-runs-properly-if-each-package-masks-functions-from-another) discusses the issue in detail.

@gwerbin Suggestions for improvement?

**Comment by gwerbin** [comment]
@ramhiser I'm aware of how masking works in R, and it's impossible to always account for it. However in both of the cases you mentioned, the newer package offers the functionality that was masked, but in another form. The main issue here isn't so much the masking as it is the inconsistency, and the fact that `itertools2` has no equivalent to `iterators::icount`. The easiest solution in my opinion would be to add an optional stopping point to `itertools2::icount`.

**Comment by ramhiser** [comment]
My apologies if I sounded pedantic. I get what you are saying, but I point you to the classic `reshape::melt` vs `reshape2::melt` example as a case where functionality differs slightly between functions that can get masked.

Regardless, I like your idea of the optional stopping point. I'll add `icount(..., stop=NULL)`. Example usage: `as.list(icount(stop=5))` equivalent to `as.list(1:5)`.
